#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd "$SCRIPT_DIR"
git pull
#git submodule update --init
git submodule update
hugo
sudo cp -r public/* /var/www/html/
